version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
  stolen-bike-catalog:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
